version: "3.9"

services:
    web:
        container_name: advanced_information_exercise
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - .:/workspace
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: /bin/sh -c "cd backend && python manage.py runserver 0.0.0.0:8000"

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: mydb
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypass
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    db-data:
